apiVersion: v1
kind: Secret
metadata:
  name: secret-db
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9kYl9odzQ=  # base64 encoded "postgresql://user:password@postgres:5432/db_hw4"
  POSTGRES_USER: dXNlcg==             # Закодировано "user" в base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ=     # Закодировано "password" в base64
#Для кодирования значения в base64 используйте команду:
#echo -n "postgresql://user:password@postgres:5432/db_hw4" | base64
#где postgres:5432 - сервис:порт
#в windows в powershell:
#[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("postgresql://user:password@postgres:5432/db_hw4"))
#cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9kYl9odzQ=
#[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("user"))
#dXNlcg==
#[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("password"))
#cGFzc3dvcmQ=
#или см. https://www.base64decode.org/

