apiVersion: v1
kind: ConfigMap
metadata:
  name: config-app-crud
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
data:
  SQLALCHEMY_TRACK_MODIFICATIONS: {{ .Values.sqlalchemyTrackModifications | quote }}    #"false"
  POSTGRES_DB: {{ .Values.postgresDB }}                                                 #db_hw4