apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres    #путь в ноде