apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-crud
  template:
    metadata:
      labels:
        app: app-crud
    spec:
      containers:
      - name: app-crud
        image: {{ .Values.image.appCRUD }}     #docker.io/puzle/app_crud:v3
        ports:
        - containerPort: {{ .Values.port.appCRUD }}    #8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: DATABASE_URL
        - name: SQLALCHEMY_TRACK_MODIFICATIONS
          valueFrom:
            configMapKeyRef:
              name: config-app-crud
              key: SQLALCHEMY_TRACK_MODIFICATIONS