apiVersion: v1
kind: Service
metadata:
  name: service-crud
spec:
  selector:
    app: app-crud
  ports:
    - protocol: TCP
      port: {{ .Values.port.appCRUD }} #8000
      targetPort: {{ .Values.port.appCRUD }} #8000
  type: NodePort
#  dependsOn:
#  - deploy_app_crud.yaml